Develop
zuri-training/MyInternApp-be-pjt-38 pull request #47
Opened 2021-07-02 10:35 UTC by yemoche

#25 Creation of registration endpoints.

2021-07-04 19:22 UTC, danielsumah requested changes
Your db.sqlite file is causing a conflict

2021-07-08 12:43 UTC, danielsumah requested changes
kindly delete db.sqlite

2021-07-08 13:17 UTC, yemoche commented
Hi Dan,

Db.sqlite3 has been removed.

cheers!

On Thu, Jul 8, 2021 at 1:43 PM danielsumah ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> kindly delete db.sqlite
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/zuri-training/MyInternApp-be-pjt-38/pull/47#pullrequestreview-702013760>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AS333BQ5VNYZA5DSPGTDBKTTWWMQNANCNFSM47WOZCZQ>
> .
>

2021-07-08 14:31 UTC, danielsumah approved these changes

2021-07-08 14:32 UTC, merged